### ISSUE TITLE
Cannot build from source: 'Version' object has no attribute 'tag'

### ISSUE THREAD

**Issue by pllim** [liberfa/pyerfa#84]
I started seeing this in `astropy` that has dev job that builds pyerfa from source.

Last successful on `main` (the failures were caused by something else): https://github.com/astropy/astropy/runs/6943091688?check_suite_focus=true

Example failure: https://github.com/astropy/astropy/runs/7010907314?check_suite_focus=true

```
Collecting pyerfa
  Cloning https://github.com/liberfa/pyerfa.git to /tmp/...
  Running command git clone --filter=blob:none --quiet https://github.com/liberfa/pyerfa.git /tmp/...
  Resolved https://github.com/liberfa/pyerfa.git to commit 2ded04a8d699db3228f29ddca7912498276ac839
  Running command git submodule update --init --recursive -q
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Traceback (most recent call last):
        File ".../pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File ".../pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File ".../pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File ".../setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File ".../setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 165, in <module>
          setuptools.setup(use_scm_version=use_scm_version, ext_modules=get_extensions())
        File ".../setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File ".../setuptools/_distutils/core.py", line 139, in setup
          _setup_distribution = dist = klass(attrs)
        File ".../setuptools/dist.py", line 477, in __init__
          _Distribution.__init__(
        File ".../setuptools/_distutils/dist.py", line 275, in __init__
          self.finalize_options()
        File ".../setuptools/dist.py", line 901, in finalize_options
          ep(self)
        File ".../setuptools/dist.py", line 922, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File ".../setuptools_scm/integration.py", line 88, in version_keyword
          _assign_version(dist, config)
        File ".../setuptools_scm/integration.py", line 57, in _assign_version
          maybe_version = _get_version(config)
        File ".../setuptools_scm/__init__.py", line 157, in _get_version
          version_string = format_version(
        File ".../setuptools_scm/version.py", line 554, in format_version
          main_version = _call_version_scheme(
        File ".../setuptools_scm/version.py", line 542, in _call_version_scheme
          result = scheme(version)
        File "erfa/_dev/scm_version.py", line 36, in _guess_next_dev
          return guess_next_version(version.tag)
        File ".../setuptools_scm/version.py", line 243, in guess_next_version
          version = _strip_local(str(tag_version.tag))
      AttributeError: 'Version' object has no attribute 'tag'
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by pllim** [comment]
setuptools v62.6.0 was released 3 days ago and setuptools_scm v7.0.2 was released 10 hours ago. 😬 

I looked into your `setup.py` and cannot understand what you are trying to do with the version parsing. Maybe it is just a matter of compatibility with setuptools_scm and/or setuptools. 🤞

**Comment by mhvk** [comment]
@avalentino - as the one who wrote the part to do with it in `setup.py`, do you have any idea what is happening with the newest `setuptools_scm`? All versions >=7 break the build. Of course, it may simply be a problem with `setuptools_scm`...

**Comment by pllim** [comment]
Hmm... I think limiting `setuptools_scm` here also limits it for all other packages in the same CI job, so it is kicking the can down the road, not a permanent solution.

**Comment by mhvk** [comment]
Yeah, that's why I asked... Though if it is an upstream bug (which seems rather likely from the little investigation I did), then it would be OK... But perhaps first let @avalentino have a look.

**Comment by mhvk** [comment]
@pllim - I think I have a fix in #85. This uses the same version constraints as astropy, so should not pose problems.

**Comment by avalentino** [comment]
@mhvk , @pllim, I reviewed the PR #85.
 It looks good to me. For sure the code is now more robust.
Thanks for taking care of it.

**Comment by pllim** [comment]
Thank you, all! I like it when problem fixes itself while I am sleeping. 😸
